print("Bienvenidos a python🐍")
print ("######Cartel 6°B######") 
print("######PROGRAMANDO######")
print("######ESTUDIANDO######")
print("######APRENDIENDO######")
print("#SE CRERAN PROYECTOS")
print("💕😙☺️😝🎇🎆🤭🐯🦁🦊🐕🦌🐾🐳")
print("                  💡              ")
print(" ##LA FRASE DEL DIA ES##")
print("EL CONOCIMIENTO ES PODER🤩") 
print("ENTONCES APLIQUEMOSLO💪🏻")
print("BIENVENIDO CICLO 2025-2026)